/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Transform options exposed to JavaScript */
export interface JsTransformOptions {
  /**
   * The module to import runtime helpers from
   * @default "solid-js/web"
   */
  moduleName?: string
  /**
   * Generate mode: "dom", "ssr", or "universal"
   * Note: "universal" is currently treated as "dom" (not a separate universal renderer output).
   * @default "dom"
   */
  generate?: string
  /**
   * Whether to enable hydration support
   * @default false
   */
  hydratable?: boolean
  /**
   * Whether to delegate events
   * @default true
   */
  delegateEvents?: boolean
  /**
   * Whether to wrap conditionals
   * @default true
   */
  wrapConditionals?: boolean
  /**
   * Whether to pass context to custom elements
   * @default true
   */
  contextToCustomElements?: boolean
  /**
   * Source filename
   * @default "input.jsx"
   */
  filename?: string
  /**
   * Whether to generate source maps
   * @default false
   */
  sourceMap?: boolean
}

/** Transform JSX source code */
export declare function transformJsx(source: string, options?: JsTransformOptions | undefined | null): TransformResult

/** Result of a transform operation */
export interface TransformResult {
  /** The transformed code */
  code: string
  /** Source map (if enabled) */
  map?: string
}
